my.data <- scan('data/iotest1.txt',encoding = 'UTF-8')
v1 <- sort(my.data)
v2 <- sort(my.data, decreasing = TRUE)
v3 <- sum(my.data)
v4 <- mean(my.data)
cat("오름차순 :",v1, '\n', sep=" ")
cat("내림차순 :",v2, '\n', sep=" ")
cat("합 : ",v3, '\n', sep="")
cat("평균 : ",v4, '\n', sep="")