getwd()
setwd('C:\\Users\\haram\\rexam\\0302')
data <- readLines('memo.txt', encoding = 'UTF-8')
print(data)
str(data)
data[1] <- gsub("[&$@!#%]", "", data[1])
data[2] <- gsub("e", "E", data[2])
data[3] <- gsub("[[:digit:]]", "", data[3])
data[4] <- gsub("[a-zA-Z]|(R )", "", data[4])
data[5] <- gsub("[1-9!<>]", "", data[5])
# gsub("[[:digit:]]|[!<>]", "", data[5])
data[6] <- gsub(" ", "", data[6])
data[7] <- gsub(pattern = "YOU", replacement = 'you', x=data[7])
data[7] <- gsub(pattern = "OK", replacement = 'ok', x=data[7])
print(data)
write(data, file="memo_new.txt")